Allow for permissions to be set in auth requests
moneyhub/moneyhub-api-client pull request #19
Opened 2021-06-21 15:33 UTC by gillyhl

Sets the permissions in the auth request body when creating an auth request.

2021-06-21 15:45 UTC, jonbride approved these changes

2021-06-22 08:25 UTC, ozamarripa requested changes
It looks good but could we also allow passing permissions for the following methods:
- https://github.com/moneyhub/moneyhub-api-client#getauthorizeurlforcreateduser
https://github.com/moneyhub/moneyhub-api-client#getauthorizeurl

2021-06-22 08:27 UTC, gillyhl commented
> It looks good but could we also allow passing permissions for the following methods:
> 
> * https://github.com/moneyhub/moneyhub-api-client#getauthorizeurlforcreateduser
>   https://github.com/moneyhub/moneyhub-api-client#getauthorizeurl

Are we able to let the permissions just be part of the claims object they set in the method? Or do we want them to pass in permissions as a separate argument and we include it in the claims for them?

2021-06-22 08:47 UTC, ozamarripa commented
I think that it would be good to have an optional parameter that will include the permissions in the claims object if provided, api clients will always have the option to pass the whole claims object if needed

2021-06-22 11:40 UTC, ozamarripa approved these changes

2021-06-22 14:42 UTC, merged